spring:
  application:
    name: interaction
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.21.32.13:3306/feedx?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: "12345678"
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
  data:
    redis:
      database: 1
      host: 10.21.32.13
      port: 6379
      timeout: 3000
      password: "12345678"

server:
  port: 8885

dubbo:
  protocol:
    name: dubbo
    port: -1
    serialization: fastjson2
  registry:
    address: nacos://10.21.32.13:8848

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.yqz.interaction.po

minio:
  bucket1:
    endpoint: http://10.21.32.13:9000
    port: 9000
    accessKey: minio
    secretKey: minio123
    bucket: feedx
    publicEndpoint: http://10.21.32.13:9000